const PRODUCTS = {
  "AC-001": {
    id: "AC-001",
    name: "Ar Condicionado Inverter 9000 BTU Elgin Eco",
    category: "Ar Condicionado",
    brand: "Elgin",
    price: 2299.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      cooling_capacity: "9000 BTU",
      type: "Inverter",
      energy_rating: "A",
      room_size: "12-18 m²",
      noise_level: "26 dB (interna)",
      refrigerant: "R32",
      wifi_control: true,
      warranty: "10 anos compressor, 2 anos pecas",
    },
    description:
      "Ar condicionado inverter com 9000 BTU de capacidade. Tecnologia inverter ajusta a velocidade do compressor para controle preciso de temperatura e ate 40% de economia de energia comparado a modelos convencionais. Operacao silenciosa a 26 dB e controle via Wi-Fi.",
  },
  "AC-002": {
    id: "AC-002",
    name: "Ar Condicionado Split 12000 BTU Midea",
    category: "Ar Condicionado",
    brand: "Midea",
    price: 1599.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      cooling_capacity: "12000 BTU",
      type: "Convencional",
      energy_rating: "C",
      room_size: "18-25 m²",
      noise_level: "38 dB (interna)",
      refrigerant: "R32",
      wifi_control: false,
      warranty: "5 anos compressor, 1 ano pecas",
    },
    description:
      "Ar condicionado split convencional com 12000 BTU. Ideal para ambientes medios a grandes. Compressor convencional funciona em potencia maxima e cicla liga/desliga para manter a temperatura. Custo menor na compra, porem consumo de energia maior que modelos inverter.",
  },
  "TV-001": {
    id: "TV-001",
    name: 'Smart TV LG OLED 55" 4K evo',
    category: "TVs",
    brand: "LG",
    price: 4999.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      screen_size: '55"',
      resolution: "4K Ultra HD (3840 x 2160)",
      panel_type: "OLED evo",
      refresh_rate: "120 Hz",
      hdr: "Dolby Vision, HDR10+",
      smart_platform: "webOS",
      hdmi_ports: "4 (HDMI 2.1)",
      speakers: "40W Dolby Atmos",
      warranty: "2 anos",
    },
    description:
      "Smart TV OLED de 55 polegadas com pixels auto-emissivos para pretos perfeitos e contraste infinito. Taxa de 120Hz ideal para games e esportes. Suporte a Dolby Vision e HDR10+ para experiencia cinematografica. webOS com acesso a todos os apps de streaming.",
  },
  "TV-002": {
    id: "TV-002",
    name: 'Smart TV Samsung Crystal 43" 4K',
    category: "TVs",
    brand: "Samsung",
    price: 1899.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      screen_size: '43"',
      resolution: "4K Ultra HD (3840 x 2160)",
      panel_type: "LED (VA)",
      refresh_rate: "60 Hz",
      hdr: "HDR10",
      smart_platform: "Tizen",
      hdmi_ports: "3 (HDMI 2.0)",
      speakers: "20W stereo",
      warranty: "2 anos",
    },
    description:
      "Smart TV 4K LED de 43 polegadas com painel VA para bom contraste em ambientes escuros. HDR10 para cores e brilho aprimorados. Tizen com acesso a Netflix, YouTube e milhares de apps. Tres portas HDMI para consoles, dispositivos de streaming e soundbars. Otima opcao para quartos e salas menores.",
  },
  "PH-001": {
    id: "PH-001",
    name: "Samsung Galaxy S24 Ultra 256GB",
    category: "Smartphones",
    brand: "Samsung",
    price: 6499.00,
    currency: "BRL",
    in_stock: false,
    restock_date: "2026-03-15",
    specs: {
      display: '6.8" Dynamic AMOLED 2X, 120Hz',
      processor: "Snapdragon 8 Gen 3",
      ram: "12 GB",
      storage: "256 GB",
      camera: "200MP principal + 50MP ultrawide + 10MP telefoto + 50MP periscope",
      battery: "5000 mAh, 45W carregamento rapido",
      os: "Android 15 com One UI",
      water_resistance: "IP68",
      warranty: "1 ano",
    },
    description:
      "Smartphone flagship com sistema de cameras de 200MP e tela Dynamic AMOLED de 6.8 polegadas a 120Hz. Snapdragon 8 Gen 3 com 12GB RAM para apps e jogos exigentes. Bateria de 5000mAh com carregamento rapido de 45W. S Pen inclusa. Atualmente fora de estoque — reposicao prevista para marco 2026.",
  },
  "PH-002": {
    id: "PH-002",
    name: "Motorola Moto G84 128GB",
    category: "Smartphones",
    brand: "Motorola",
    price: 1299.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      display: '6.5" pOLED, 120Hz',
      processor: "Snapdragon 695",
      ram: "8 GB",
      storage: "128 GB (expansivel via microSD)",
      camera: "50MP principal + 8MP ultrawide",
      battery: "5000 mAh, 33W TurboPower",
      os: "Android 15",
      water_resistance: "IP54",
      warranty: "1 ano",
    },
    description:
      "Smartphone intermediario com tela pOLED de 6.5 polegadas e 120Hz para uso fluido no dia a dia. Snapdragon 695 com 8GB RAM para redes sociais, mensagens e jogos casuais. Camera de 50MP com boas fotos em ambientes iluminados. Bateria de 5000mAh com carregamento TurboPower de 33W que dura o dia todo.",
  },
  "WM-001": {
    id: "WM-001",
    name: "Maquina de Lavar Brastemp 12kg",
    category: "Maquinas de Lavar",
    brand: "Brastemp",
    price: 2899.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      capacity: "12 kg",
      type: "Abertura Superior",
      spin_speed: "800 RPM",
      energy_rating: "A",
      wash_programs: 12,
      steam_wash: false,
      inverter_motor: true,
      noise_level: "52 dB (lavagem) / 70 dB (centrifugacao)",
      warranty: "10 anos motor, 2 anos pecas",
    },
    description:
      "Maquina de lavar de 12kg com motor inverter para operacao silenciosa e eficiente. 12 programas de lavagem incluindo roupas delicadas e edredons. Centrifugacao de 800 RPM para secagem mais rapida. Sensor automatico ajusta nivel de agua e quantidade de sabao.",
  },
  "SH-001": {
    id: "SH-001",
    name: "Tenis Olympikus Corre Pro 3",
    category: "Calcados",
    brand: "Olympikus",
    price: 399.90,
    currency: "BRL",
    in_stock: true,
    specs: {
      type: "Corrida",
      upper_material: "Tela engineered mesh com reforcos em TPU",
      sole: "Borracha Fylon com placa de carbono",
      cushioning: "Espuma CORRE+ dupla densidade",
      drop: "8mm",
      weight: "260g (tamanho 42)",
      waterproof: "Nao",
      available_sizes: "37-45",
      colors: ["Preto/Laranja", "Cinza/Azul", "Verde/Preto"],
      warranty: "90 dias",
    },
    description:
      "Tenis de corrida de alta performance com solado Fylon e placa de carbono para retorno de energia. Cabedal em mesh engineered com reforcos em TPU para respirabilidade e suporte. Entressola CORRE+ de dupla densidade para absorcao de impacto. Drop de 8mm para pisada natural.",
  },
  "SH-002": {
    id: "SH-002",
    name: "Tenis Casual Reserva Go Urban",
    category: "Calcados",
    brand: "Reserva",
    price: 289.90,
    currency: "BRL",
    in_stock: true,
    specs: {
      type: "Casual",
      upper_material: "Couro sintetico premium",
      sole: "Borracha TR",
      cushioning: "Palmilha OrthoComfort",
      drop: "10mm",
      weight: "340g (tamanho 42)",
      waterproof: "Nao",
      available_sizes: "38-44",
      colors: ["Branco", "Branco/Marinho", "Preto"],
      warranty: "90 dias",
    },
    description:
      "Tenis casual minimalista em couro sintetico premium que desenvolve patina natural com o uso. Palmilha OrthoComfort oferece amortecimento e controle de umidade para conforto o dia todo. Solado de borracha TR com desenho espinha de peixe para boa tracao em ruas. Design limpo e versatil combina com jeans, chinos ou looks casuais.",
  },
  "LP-001": {
    id: "LP-001",
    name: 'Notebook Acer Nitro 5 15.6"',
    category: "Laptops",
    brand: "Acer",
    price: 5499.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      display: '15.6" IPS, 1920x1080, 144Hz',
      processor: "Intel Core i5-13450H",
      gpu: "NVIDIA RTX 4050 6GB",
      ram: "16 GB DDR5",
      storage: "512 GB NVMe SSD",
      battery: "57 Wh, ate 6 horas",
      weight: "2.5 kg",
      os: "Windows 11 Home",
      ports: "1x USB-C, 3x USB-A, HDMI 2.0, RJ45",
      warranty: "1 ano",
    },
    description:
      "Notebook gamer com Intel Core i5 13a geracao e RTX 4050 para jogos e trabalho. Tela IPS de 15.6 polegadas Full HD a 144Hz para visuais fluidos. 16GB DDR5 e SSD NVMe de 512GB para multitarefa rapida. Teclado com iluminacao RGB e conectividade completa.",
  },
  "LP-002": {
    id: "LP-002",
    name: 'Notebook Dell Inspiron 14" Ultrabook',
    category: "Laptops",
    brand: "Dell",
    price: 3799.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      display: '14" IPS, 1920x1200, 60Hz',
      processor: "Intel Core i7-1355U",
      gpu: "Intel Iris Xe integrada",
      ram: "16 GB LPDDR5",
      storage: "512 GB NVMe SSD",
      battery: "54 Wh, ate 10 horas",
      weight: "1.5 kg",
      os: "Windows 11 Home",
      ports: "2x USB-C (Thunderbolt 4), 1x USB-A, HDMI 1.4",
      warranty: "1 ano",
    },
    description:
      "Ultrabook leve de 14 polegadas com tela IPS de resolucao 1920x1200. Pesa apenas 1.5kg para maxima portabilidade. Intel Core i7 13a geracao para tarefas de produtividade. Bateria de 54Wh com ate 10 horas de uso. Ideal para profissionais e estudantes.",
  },
  "HP-001": {
    id: "HP-001",
    name: "Fone de Ouvido JBL Tune 770NC Bluetooth",
    category: "Fones de Ouvido",
    brand: "JBL",
    price: 449.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      type: "Over-ear, Sem Fio",
      driver_size: "40mm",
      frequency_response: "20Hz - 20kHz",
      anc: "Cancelamento de Ruido Ativo Adaptativo",
      battery: "44 horas (ANC ligado), 70 horas (ANC desligado)",
      charging: "USB-C, carga rapida 5 min = 3 horas",
      bluetooth: "5.3 com multipoint (2 dispositivos)",
      codec: "AAC, SBC",
      weight: "225g",
      warranty: "1 ano",
    },
    description:
      "Fone de ouvido sem fio premium com cancelamento de ruido ativo adaptativo. Drivers de 40mm com som JBL Pure Bass. 44 horas de bateria com ANC ligado. Bluetooth 5.3 multipoint para alternar entre dois dispositivos. Carga rapida de 5 minutos para 3 horas de reproducao.",
  },
  "HP-002": {
    id: "HP-002",
    name: "Fone de Ouvido Bluetooth QCY T13 ANC",
    category: "Fones de Ouvido",
    brand: "QCY",
    price: 149.90,
    currency: "BRL",
    in_stock: false,
    restock_date: "2026-02-28",
    specs: {
      type: "In-ear, True Wireless",
      driver_size: "10mm",
      frequency_response: "20Hz - 20kHz",
      anc: "Cancelamento de Ruido Ativo Hibrido",
      battery: "7.5 horas (fone), 30 horas (com estojo)",
      charging: "USB-C",
      bluetooth: "5.3",
      codec: "AAC, SBC",
      water_resistance: "IPX5",
      weight: "4.7g por fone",
      warranty: "1 ano",
    },
    description:
      "Fone de ouvido true wireless compacto com ANC hibrido e drivers de 10mm para graves profundos. Resistencia IPX5 para treinos e dias chuvosos. 7.5 horas de bateria por carga com mais 22.5 horas do estojo. Leve com apenas 4.7g por fone para conforto o dia todo. Atualmente fora de estoque — reposicao prevista para final de fevereiro 2026.",
  },
  "RF-001": {
    id: "RF-001",
    name: "Geladeira Consul Frost Free Duplex 410L",
    category: "Geladeiras",
    brand: "Consul",
    price: 2799.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      capacity: "410 litros (300L refrigerador / 110L freezer)",
      type: "Duplex, freezer em cima",
      compressor: "Inverter",
      energy_rating: "A",
      cooling_system: "Multi Air Flow",
      noise_level: "37 dB",
      dimensions: "690 x 1780 x 640 mm (L x A x P)",
      features: "Prateleiras regulaveis, gaveta de frutas e legumes, iluminacao LED",
      warranty: "10 anos compressor, 1 ano pecas",
    },
    description:
      "Geladeira duplex frost free de 410 litros com compressor inverter para operacao silenciosa e eficiente a apenas 37 dB. Sistema Multi Air Flow mantem temperatura uniforme em todos os cantos. Prateleiras regulaveis e gaveta para frutas e legumes com controle de umidade.",
  },
  "RF-002": {
    id: "RF-002",
    name: "Geladeira Electrolux French Door 579L com Dispenser",
    category: "Geladeiras",
    brand: "Electrolux",
    price: 7999.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      capacity: "579 litros (390L refrigerador / 189L freezer)",
      type: "French Door",
      compressor: "Inverter digital",
      energy_rating: "A",
      cooling_system: "Twin Cooling Plus",
      ice_maker: "Dispenser de agua e gelo automatico",
      noise_level: "39 dB",
      dimensions: "912 x 1785 x 750 mm (L x A x P)",
      smart_features: "Wi-Fi, painel touch",
      warranty: "10 anos compressor, 2 anos pecas",
    },
    description:
      "Geladeira premium French Door de 579 litros com sistema Twin Cooling que mantem temperatura e umidade independentes no refrigerador e freezer. Dispenser de agua e gelo embutido. Conectividade Wi-Fi e painel touch para integracao com casa inteligente.",
  },
  "TB-001": {
    id: "TB-001",
    name: 'Tablet Samsung Galaxy Tab S6 Lite 10.4"',
    category: "Tablets",
    brand: "Samsung",
    price: 1899.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      display: '10.4" TFT, 2000x1200, 60Hz',
      processor: "Exynos 1280",
      ram: "4 GB",
      storage: "64 GB (expansivel via microSD)",
      camera: "8MP traseira + 5MP frontal",
      battery: "7040 mAh, 15W carregamento",
      os: "Android 15 com One UI",
      connectivity: "Wi-Fi 5, Bluetooth 5.0",
      stylus_support: true,
      weight: "467g",
      warranty: "1 ano",
    },
    description:
      "Tablet versatil de 10.4 polegadas com caneta S Pen inclusa para anotacoes e desenho. Exynos 1280 com 4GB RAM para multitarefa basica e apps em tela dividida. Bateria de 7040mAh com ate 13 horas de video. Armazenamento expansivel via microSD.",
  },
  "TB-002": {
    id: "TB-002",
    name: 'Tablet Samsung Galaxy Tab S9 FE 10.9"',
    category: "Tablets",
    brand: "Samsung",
    price: 3299.00,
    currency: "BRL",
    in_stock: false,
    restock_date: "2026-04-01",
    specs: {
      display: '10.9" TFT, 2304x1440, 90Hz',
      processor: "Exynos 1380",
      ram: "6 GB",
      storage: "128 GB (expansivel via microSD)",
      camera: "8MP traseira + 12MP frontal",
      battery: "8000 mAh, 15W carregamento",
      os: "Android 15 com One UI",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      stylus_support: true,
      water_resistance: "IP68",
      weight: "523g",
      warranty: "1 ano",
    },
    description:
      "Tablet premium de 10.9 polegadas com tela 90Hz e resistencia a agua IP68. Exynos 1380 com 6GB RAM para desempenho avancado. S Pen inclusa para produtividade. Bateria de 8000mAh com ate 15 horas de uso. Atualmente fora de estoque — reposicao prevista para abril 2026.",
  },
  "CM-001": {
    id: "CM-001",
    name: "Camera Mirrorless Canon EOS R50 (corpo)",
    category: "Cameras",
    brand: "Canon",
    price: 4299.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      sensor: "24.2 MP APS-C CMOS",
      processor: "DIGIC X",
      iso_range: "100-32000 (expansivel ate 51200)",
      autofocus: "AF Dual Pixel CMOS II, deteccao de olhos/animais",
      video: "4K 30fps, 1080p 120fps",
      stabilization: "Estabilizacao digital de video",
      viewfinder: "EVF OLED 2.36M pontos",
      display: '3.0" touch articulado',
      card_slot: "SD UHS-I",
      weight: "375g (corpo)",
      warranty: "1 ano",
    },
    description:
      "Camera mirrorless compacta com sensor APS-C de 24.2MP e processador DIGIC X para desempenho rapido e preciso. AF Dual Pixel CMOS II com deteccao de olhos e animais. Gravacao de video 4K e tela touch articulada ideal para criadores de conteudo e entusiastas de fotografia.",
  },
  "WM-002": {
    id: "WM-002",
    name: "Lava e Seca Samsung 11kg AddWash",
    category: "Maquinas de Lavar",
    brand: "Samsung",
    price: 3899.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      capacity: "11 kg lavagem / 7 kg secagem",
      type: "Lava e Seca Frontal",
      spin_speed: "1400 RPM",
      energy_rating: "A",
      wash_programs: 14,
      steam_wash: true,
      inverter_motor: true,
      noise_level: "50 dB (lavagem) / 62 dB (centrifugacao)",
      warranty: "10 anos motor, 1 ano pecas",
    },
    description:
      "Lava e seca com porta AddWash para adicionar roupas durante o ciclo. Motor inverter digital com 11kg para lavagem e 7kg para secagem. 14 programas incluindo lavagem a vapor para higienizacao profunda. Ecobubble dissolve o sabao em bolhas para limpeza eficiente em agua fria.",
  },
  "RV-001": {
    id: "RV-001",
    name: "Robo Aspirador Xiaomi Robot Vacuum S10+",
    category: "Aspiradores Robo",
    brand: "Xiaomi",
    price: 2199.00,
    currency: "BRL",
    in_stock: true,
    specs: {
      suction_power: "4000 Pa",
      navigation: "LiDAR + camera 3D",
      battery: "4000 mAh, ate 130 min",
      dustbin: "450 ml (base auto-esvaziamento inclusa)",
      water_tank: "200 ml (controle eletronico de agua)",
      mopping: "Mop vibratório, 3000 RPM",
      noise_level: "62 dB (modo padrao)",
      mapping: "Mapeamento multi-andar, zonas proibidas",
      smart_features: "Wi-Fi, app Mi Home, compativel com Alexa/Google",
      warranty: "1 ano",
    },
    description:
      "Robo aspirador e passa pano combo com succao de 4000Pa e navegacao LiDAR para mapeamento preciso. Base auto-esvaziamento comporta ate 60 dias de poeira. Mop vibratorio a 3000 RPM para manchas em pisos duros. Mapeamento multi-andar com zonas proibidas configuráveis pelo app. Autonomia de 130 minutos cobre casas grandes em uma unica carga.",
  },
};

const ORDERS = {
  "ORD-10001": {
    order_id: "ORD-10001",
    customer_name: "Carlos Silva",
    product_id: "AC-001",
    product_name: "Ar Condicionado Inverter 9000 BTU Elgin Eco",
    status: "enviado",
    tracking_number: "BR20260205XYZ",
    carrier: "Correios (SEDEX)",
    estimated_delivery: "2026-02-15",
    order_date: "2026-02-05",
  },
  "ORD-10002": {
    order_id: "ORD-10002",
    customer_name: "Ana Beatriz Santos",
    product_id: "TV-001",
    product_name: 'Smart TV LG OLED 55" 4K evo',
    status: "em processamento",
    tracking_number: null,
    carrier: null,
    estimated_delivery: "2026-02-18",
    order_date: "2026-02-08",
  },
  "ORD-10003": {
    order_id: "ORD-10003",
    customer_name: "Roberto Ferreira",
    product_id: "SH-001",
    product_name: "Tenis Olympikus Corre Pro 3",
    status: "entregue",
    tracking_number: "BR20260201ABC",
    carrier: "Jadlog",
    estimated_delivery: "2026-02-04",
    delivered_date: "2026-02-03",
    order_date: "2026-02-01",
  },
};

const SUPPORT_DEPARTMENTS = {
  trocas: {
    department: "Trocas e Devolucoes",
    phone: "(11) 3456-7890 ramal 1",
    email: "trocas@techstore.exemplo.br",
    hours: "Seg-Sex 9:00-18:00",
  },
  garantia: {
    department: "Garantia e Reparos",
    phone: "(11) 3456-7890 ramal 2",
    email: "garantia@techstore.exemplo.br",
    hours: "Seg-Sex 9:00-18:00",
  },
  entrega: {
    department: "Entrega e Logistica",
    phone: "(11) 3456-7890 ramal 3",
    email: "entrega@techstore.exemplo.br",
    hours: "Seg-Sab 8:00-20:00",
  },
  pagamento: {
    department: "Pagamento e Cobranca",
    phone: "(11) 3456-7890 ramal 4",
    email: "pagamento@techstore.exemplo.br",
    hours: "Seg-Sex 9:00-17:00",
  },
  geral: {
    department: "Atendimento Geral",
    phone: "(11) 3456-7890",
    email: "atendimento@techstore.exemplo.br",
    hours: "Seg-Dom 8:00-22:00",
  },
};

module.exports = { PRODUCTS, ORDERS, SUPPORT_DEPARTMENTS };
